- hosts: dockertesting
  become: yes
  tasks:
    - name: Build dockertesting
      docker_image:
        name: dockertesting
        path: ../docker-testing

    - name: Start dockertesting container
      docker_container:
        name: dockertesting
        image: dockertesting
        network_mode: host
        detach: yes
        restart_policy: always
        volumes:
          - "../docker-testing:/docker-testing"
